#define GRANTLEE_VERSION_MAJOR @KTextTemplate_VERSION_MAJOR@
#define GRANTLEE_VERSION_MINOR @KTextTemplate_VERSION_MINOR@
#define GRANTLEE_VERSION_PATCH @KTextTemplate_VERSION_PATCH@
#define GRANTLEE_VERSION_STRING "@KTextTemplate_VERSION@"
#define GRANTLEE_VERSION ((@KTextTemplate_VERSION_MAJOR@<<16)|(@KTextTemplate_VERSION_MINOR@<<8)|(@KTextTemplate_VERSION_PATCH@))
#define GRANTLEE_MAJOR_MINOR_VERSION_STRING "@KTextTemplate_MAJOR_MINOR_VERSION_STRING@"
#define GRANTLEE_MIN_PLUGIN_VERSION @KTextTemplate_MIN_PLUGIN_VERSION@
