#define KTEXTTEMPLATE_VERSION_MAJOR @KTextTemplate_VERSION_MAJOR@
#define KTEXTTEMPLATE_VERSION_MINOR @KTextTemplate_VERSION_MINOR@
#define KTEXTTEMPLATE_VERSION_PATCH @KTextTemplate_VERSION_PATCH@
#define KTEXTTEMPLATE_VERSION_STRING "@KTextTemplate_VERSION@"
#define KTEXTTEMPLATE_VERSION ((@KTextTemplate_VERSION_MAJOR@<<16)|(@KTextTemplate_VERSION_MINOR@<<8)|(@KTextTemplate_VERSION_PATCH@))
